version: '3'
services:
  postgres:
    image: postgres:11
    container_name: 'boilerplate_queue_db'
    volumes:
      - boilerplate-queue:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=boilerplate
      - POSTGRES_DB=boiler_queue
      - POSTGRES_PORT=5433
    ports:
      - 5433:5432
    networks:
      - net

  boilerplate:
    image: node:11
    container_name: 'boilerplate_queue'
    build: .
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      DB_HOST: host.docker.internal
    volumes:
      - .:/app/
    ports:
      - 5000:5000
    working_dir: /app/
    network_mode: host
    command: npm run dev

  redis:
    container_name: redis_queue
    environment:
      REDIS_HOST: redis
    image: redis
    ports:
      - "6379:6379"

volumes:
  boilerplate-queue:

networks:
  net:
    driver: bridge